### ISSUE TITLE
xochitl web interface not running version 3.13

### ISSUE THREAD

**Issue by mohamed25051991** [rM-self-serve/webinterface-onboot#5]
xochitl not running version 3.13

**Comment by rM-self-serve** [comment]
Please ensure you have followed the instructions in the readme. If you struggle doing so, please open a support thread in discord. If you find you still have an issue, you can reopen this and provide information on the issue, the version is not enough.

If this issue was true, your device would be soft-bricked or require the company's support. Please try the built in `--status` command when debugging your installation.

**Comment by mohamed25051991** [comment]
resolved after restart xochitl
